name: Fetch WS 2025 Data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v3 -> SHA 값으로 변경
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      # actions/setup-python@v4 -> SHA 값으로 변경
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ee83502
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run Fetch Script
        run: python scripts/fetch_ws_data.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/ws_2025_backtest.csv
          git commit -m "Update 2025 WS Backtest Data" || echo "No changes to commit"
          git push
