name: MLB Stock Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 외부 액션 대신 시스템 명령어로 처리 시도
      - name: 체크아웃 코드
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: 라이브러리 직접 설치 및 코드 실행
        run: |
          python3 -m pip install requests pandas
          python3 update_stock.py

      - name: 업데이트된 파일 저장(Commit)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update stock data" || echo "No changes to commit"
          git push
